<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Anils-MacBook-Air.local" failures="1" tests="7" name="Default test" time="44.258" errors="0" timestamp="1 Aug 2018 00:12:04 GMT">
  <testcase classname="com.channelassist.tests.TestNGTests" name="selectandVerifyProductPage" time="2.708">
    <failure type="java.lang.AssertionError" message="expected [Product Category] but found [Product ategory]">
      <![CDATA[java.lang.AssertionError: expected [Product Category] but found [Product ategory]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at com.channelassist.tests.TestNGTests.selectandVerifyProductPage(TestNGTests.java:56)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- selectandVerifyProductPage -->
  <testcase classname="com.channelassist.tests.TestNGTests" name="selectandVerifyAccessoriesPage" time="3.489"/>
  <testcase classname="com.channelassist.tests.TestNGTests" name="selectMagicMouse" time="6.394"/>
  <testcase classname="com.channelassist.tests.TestNGTests" name="addtocart" time="0.113"/>
  <testcase classname="com.channelassist.tests.TestNGTests" name="verifyQuantityandCheckout" time="6.51"/>
  <testcase classname="com.channelassist.tests.TestNGTests" name="billingDetailsDataDriven" time="2.322"/>
  <testcase classname="com.channelassist.tests.TestNGTests" name="purchaseandValidate" time="14.95"/>
</testsuite> <!-- Default test -->
